permissions:
  - '*'
jobs:
  main:
    steps:
      - name: Generate Windows S3 Credentials
        run: |
          source /etc/profile.d/parallelworks.sh
          source /etc/profile.d/parallelworks-env.sh
          source /pw/.miniconda3/etc/profile.d/conda.sh
          python3 bucket_token_generator.py --bucket_id ${{ inputs.bucket_id }} --token_format text --platform windows
'on':
  execute:
    inputs:
      bucket_id:
        label: Bucket ID or namespace
        type: string
        tooltip: Type in the bucket ID string or namespace in the format [bucket-owner]/[bucket-name]
